exp:
  name: SAMamba
  save_exp: True
  bs: 4
  total_epochs: 300
  log_interval: 1
  save_interval: 100
  test_interval: 1
  device: 0
model:
  net:
    type: SAMamba

  optim:
    type: AdamW
#    init_lr: !!float 1e-3
    init_lr: !!float 5e-4
    weight_decay: !!float 1e-4
    betas: [0.9, 0.999]
  loss:
    loss_1:
      type: SoftIoULoss
      weight: 1
    loss_2:
      type: WeightedDiceLoss
      weight: 1
    loss_3:
      type: FocalLoss
      weight: 1
#   resume_train: ~
  lr:
    warmup_iter: -1 # warmup to init_lr
    # type: CosineAnnealingLR /
    scheduler:
#      type: ~
      type: CosineAnnealingLR
      step_interval: iter  # iter or epoch (every iter or every epoch to update once)
      eta_min: !!float 1e-5

dataset:
  name:
  train:
    type: Dataset_aug_bac
    data_root: /media/data2/zhengshuchen/code/SIRST/trainval
    img_sz: 1024

  test:
    type: Dataset_test
    data_root: /media/data2/zhengshuchen/code/SIRST/test
    img_sz: 1024

resume:
  net_path: 
  state_path: